baseURL = "https://ryanjansen.me/"
languageCode = "en-us"

theme = 'hugo-bearblog'

title = "Ryan Jansen"
author = "Ryan Jansen"
copyright = "Copyright @ 2021 Ryan Jansen"

enableRobotsTXT = true

disableKinds=["taxnomy"]
[permalinks]
  blog = "/:slug/"
  tags = "/blog/:slug"

[params]
  # The "description" of your website. This is used in the meta data of your generated html.
  description = "The website of Ryan Jansen, current undergraduate CS Student at NUS."

  # The path to your "favicon". This should be a square (at least 32px x 32px) png-file.
  # Hint: It's good practise to also put a "favicon.ico"-file into your "static"-folder.
  favicon = "images/favicon.png"

  # These "images" are used for the structured data templates. This will show up, when
  # services like Twitter or Slack want to generate a preview of a link to your site.
  # See https://gohugo.io/templates/internal#twitter-cards and
  # https://gohugo.io/templates/internal#open-graph.
  images = ["images/share.png"]

