So it's been a week since I've returned from TMC, or technical mountaineering course. I'm still processing what happened during the trip. Because so much happened that I wasn't prepared for. On one hand it was an amazing experience. How often do you get to stand on the top of a 5800m mountain? And on the other it was a tiring, draining slog to simply reach the starting point. Here is my experience of the whole trip.

We started in Nepal's hectic capital, Kathmandu. Our guesthouse was located centrally in Thamel, the tourist area of the city. On the first day most of the guys decided to take a 2am stroll through the streets on the lookout for food, which I kindly declined as I thought that wandering through a foreign city at night was not the best of ideas. They had a colorful experience but came out none the worse for wear.

The next day we thoroughly explored the city. We started by walking the streets, narrowly avoiding cars and scooters rushing by. From browsing in a bookstore to seeing a mobile pet store, there was no shortage of things to see and do. In the latter half of the day we decided it would be fun to rent some scooters and head to the nearby monkey temple. What ensured was a stressful ride through the winding streets of Kathmandu, thankfully with no major incidents along the way.

The night ended with a multi course Nepalese dinner, coupled with their local liquer called raksi. After 5 shots of it, we were all inclined to join the performers on stage and drunkenly imitate a traditional dance to finish off our time in Kathmandu.

Having had our fun, we embarked on towards our next destination, the town of Syabrubesi. The 7 hour bus ride was long and tiring but we were rewarded with our first views of the rolling hills and vast landscapes of Nepal. Having left my earpieces in my bag which was now sandwiched under 5 other bags at the back of the bus, I had no choice but to sit and wait for the ride to end. In the end we made it in one piece, even though we had some close calls on the narrow mountain roads.

As night fell we went to one of the village stores and got 3 bottles of gorkha extra strong beer (which we had discovered the day before) to hold a small memorial service for Giovanni's dog, Yuki, who had passed a few hours ago. Then we went on a nighttime expedition around the area, venturing into a mining tunnel that became hotter and more humid the deeper we went in. Fearing that it would collapse, we hurried the hell out of there.

The next day the real trek began. We split into teams of four, with my team consisting of me, Santhya, Paul and Kok Hai. Our team name was team beast, after Santhya who was a beast during our Sunday hill trainings. We were led by our guide Manu, who had been with the past 5 TMCs. As we set off, a particularly friendly pack of dogs started following us. They would end up going all the way to our first rest stop. 

The hiking was tough but manageable. Our loads were light thanks to the help of our amazing porters, who casually carried 3 of our 20kg packs at one go and overtook us on the trail. I have serious respect for them, especially since they aren't paid very much. The trek felt like an extended version of Bukit Timah hill, and by extended I mean up to 7 hrs of hiking in one day, most of it uphill. 

For lunch we had 